-- Migration: Add vouchers/promotions table for user redemption
-- Run in Supabase SQL editor

CREATE TABLE IF NOT EXISTS public.vouchers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  code TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  discount_value INTEGER NOT NULL,
  min_purchase INTEGER DEFAULT 0,
  max_usage INTEGER DEFAULT 0, -- 0 = unlimited
  used_count INTEGER DEFAULT 0,
  valid_from TIMESTAMP WITH TIME ZONE NOT NULL,
  valid_until TIMESTAMP WITH TIME ZONE NOT NULL,
  active BOOLEAN DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes untuk query cepat
CREATE INDEX IF NOT EXISTS idx_vouchers_code ON public.vouchers(code);
CREATE INDEX IF NOT EXISTS idx_vouchers_active ON public.vouchers(active);
CREATE INDEX IF NOT EXISTS idx_vouchers_valid_range ON public.vouchers(valid_from, valid_until);

-- Tabel redemption history (optional, untuk track siapa pakai voucher apa)
CREATE TABLE IF NOT EXISTS public.voucher_redemptions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  voucher_id BIGINT NOT NULL REFERENCES public.vouchers(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  order_id UUID NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  discount_amount INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_redemptions_voucher ON public.voucher_redemptions(voucher_id);
CREATE INDEX IF NOT EXISTS idx_redemptions_user ON public.voucher_redemptions(user_id);
CREATE INDEX IF NOT EXISTS idx_redemptions_order ON public.voucher_redemptions(order_id);

-- Enable RLS
ALTER TABLE public.vouchers ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voucher_redemptions ENABLE ROW LEVEL SECURITY;

-- RLS Policy: Anyone can view active vouchers
CREATE POLICY "Anyone can view active vouchers"
  ON public.vouchers FOR SELECT
  USING (active = true);

-- RLS Policy: Only admins can manage vouchers
-- (Pastikan ada kolom is_admin di auth.users atau gunakan custom claim)
CREATE POLICY "Only admins can manage vouchers"
  ON public.vouchers
  FOR ALL
  USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE id = auth.uid()
        AND raw_user_meta_data->>'is_admin' = 'true'
    )
  );

-- RLS Policy: Users can only view their own redemptions
CREATE POLICY "Users can view their redemptions"
  ON public.voucher_redemptions FOR SELECT
  USING (user_id = auth.uid());

-- RLS Policy: Only backend can insert redemptions
-- (Lebih aman via stored procedure atau backend endpoint)
CREATE POLICY "System can insert redemptions"
  ON public.voucher_redemptions FOR INSERT
  WITH CHECK (true);

-- Trigger untuk auto-update updated_at
CREATE OR REPLACE FUNCTION update_vouchers_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_vouchers_updated_at
  BEFORE UPDATE ON public.vouchers
  FOR EACH ROW
  EXECUTE FUNCTION update_vouchers_timestamp();
